"""Examples for constraints and hash-locked installs."""

# Install using a constraints file
# python -m pip install -r requirements.txt -c constraints.txt

# Example hash line in requirements (generated by pip-compile/pip-tools)
# somepackage==1.2.3 --hash=sha256:...

# TODO: add generator commands and a maintenance checklist.